default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD']%>
  host: db
  port: 5432
development:
  <<: *default
  database: e1_development
test:
  <<: *default
  database: e1_test
production:
  primary: &primary_production
    <<: *default
    database: e1_production
    username: e1
    password: <%= ENV["E1_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: e1_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: e1_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: e1_production_cable
    migrations_paths: db/cable_migrate
